### ISSUE TITLE
Create TestConnection API route for Plugins in Config UI (Jenkins, GitLab, Jira)

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#595] opened 2021-11-02 18:06 UTC
## Description
This will provide an API route for the frontend to test whether or not the currently saved credentials work on the Plugin's API.

## Describe the solution you'd like
I would like to implement an API resource on each plugin that responds to a GET request to "plugins/<plugin-name>/testConnection" by making the simplest possible request to the third-party API to test that the provided authentication token returns a valid response and therefore can be used for collection purposes.

## Has the Feature been Requested Before?
No.

**Comment by joncodo** [comment] 2021-11-22 13:43
Duplicate of https://github.com/merico-dev/lake/issues/667

**Closed by joncodo** 2021-11-22 13:43 UTC
Labels: proposal, Frontend, iter5, usability
