### ISSUE TITLE
not collecting jira_issue_commits but we should be?

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1088] opened 2022-01-20 17:45 UTC
<img width="913" alt="Screen Shot 2022-01-20 at 10 18 04 AM" src="https://user-images.githubusercontent.com/3011407/150393065-2a7ea1e3-14ac-4e26-b786-47624240928f.png">

<img width="526" alt="Screen Shot 2022-01-20 at 1 46 29 PM" src="https://user-images.githubusercontent.com/3011407/150393368-bf483284-e264-4242-ade7-f16055861102.png">

The code is being called but no data is in the DB. I think this code is still being used but I need confirmation from @klesh who wrote this 22 days ago.

### Steps to reproduce:
1. Run all services locally (make dev)
2. Collect from Jira board 8
3. Check the db for records in jira_issue_commits

### Expected:
There should be data

### Actual:
There is no data

**Comment by klesh** [comment] 2022-01-21 14:59
@joncodo i think it might be caused by the `diff sync`  feature, try to truncate the `jira_issues` table and recollect.

**Comment by warren830** [comment] 2022-03-04 01:35
Can we close this ?

**Comment by klesh** [comment] 2022-03-08 01:04
I think so, feel free to reopen if problem still exists

**Closed by klesh** 2022-03-08 01:04 UTC
Labels: type/bug
