### ISSUE TITLE
Give User the Sense of Progress

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#822] opened 2021-11-18 15:11 UTC
## Description
Currently, our UI gives the User the false impression that the plugin is not making progress even when it is making progress. This is because it is relying exclusively on the "progress" updates from the Tasks that are running. For example, the plugin will update progress in this manner between subtasks:

Plugin Start
Progress = 0
Big task
Progress = 20%
Small task
Progress = 30%
Huge task
Progress = 80%
Big task
Progress = 100%

Thus, the user in this scenario will see "30%" displayed for a long time, and they will not know if the app has hung. This is a bad UX.

## Describe the solution you'd like

~~I propose (after discussions with @joncodo) that we give the User the sense of progress on the front end by incrementing the progress by a very small percentage every few seconds in between task progress updates from the backend. So it would instead look something like this:~~

~~Plugin Start~~
~~Progress = 0~~
~~Big task~~
~~Progress = 20%~~
~~Frontend says...20.1%... 20.2%...20.3%....~~
~~Small task~~
~~Progress = 30%~~
~~Frontend says...30.1%... 30.2%...30.3%....~~
~~Huge task~~
~~Progress = 80%~~
~~Frontend says...80.1%... 80.2%...80.3%....~~
~~Big task~~
~~Progress = 100%~~

~~We choose a very small increment so that it never reaches the next progress limit before collection does. We can supply the frontend with progress increments via an API route so that this never happens.~~

## Final Decision

1. Framework is to provide some kind of facility for plugin to write logs, this facility require plugin to declare current ask name, and a optional total number of collected records.
2. All plugin should adopt this logging facility
3. Framework is to provide some sort of api for `config-ui` to request logs for a specific task/pipeline, and this api must be able to accept some kind of offset parameter so logs that already been sent will not need to be resent anymore. so `config-ui` can provide some kind of progressive logging interface
4. Framework is to provide some sort of api for `config-ui` to request latest status for a specific task/pipeline, so  `config-ui` can provide some kind of progressive overall status interface like following
```
Step 1/9: Collecting Commits (150 so far...)
or
Step 3/9: Collecting Issues (1500 so far...)
```

## Has the Feature been Requested Before?
No.

## Describe alternatives you've considered
- https://github.com/merico-dev/lake/issues/789

However, the solution I propose here seems much more direct and simpler. As discussed, solution #789 has a serious problem in the scenarios where we cannot get information from the plugin API about how long progress should actually take, and this varies from plugin to plugin, and task to task. Therefore, the frontend solution accomplishes the goal of letting the User know the task has not failed and is still making progress. Of course if anything causes the task to fail, the frontend will know about it.

## Additional Context

@e2corporation If you have other ideas about implementation, please share them since this is a UI task. The implementation can be different but the idea is to make sure the User knows progress is happening and not stopped.

**Comment by joncodo** [comment] 2021-11-19 18:15
Spinners are fine

**Comment by joncodo** [comment] 2021-11-19 18:19
@Startrekzky Can we talk about this on a call?

**Comment by joncodo** [comment] 2021-11-19 18:25
From @hezyin - We could tell them how many phases we have and how many records we have collected. We just don't know the total

IE: 

```
Step 1/9: Collecting Commits (150 so far...)
or
Step 3/9: Collecting Issues (1500 so far...)
```

**Comment by klesh** [comment] 2021-11-22 04:17
> From @hezyin - We could tell them how many phases we have and how many records we have collected. We just don't know the total
> 
> IE:
> 
> ```
> Step 1/9: Collecting Commits (150 so far...)
> or
> Step 3/9: Collecting Issues (1500 so far...)
> ```

Maybe we could also append latest logging line to the right, so user can somehow project the overall progress based one the id like:

```
Step 3/9: Collecting Issues (1500 so far...) requesting issue 1263 from api
```

This would also help us to standardize our loggin format.

PS: progress tracking should be implemented via socket.io if possible.

**Comment by joncodo** [comment] 2021-11-22 14:02
Ok. If @Startrekzky can approve this design, we will implement it.

**Comment by Startrekzky** [comment] 2021-11-24 03:49
> Ok. If @Startrekzky can approve this design, we will implement it.

I like the design. However, we don't have much time left for iter5, so we moved it to iter6.

**Comment by klesh** [comment] 2022-04-24 07:05
backend part was ready: https://github.com/merico-dev/lake/issues/1423

**Comment by tanninghan** [comment] 2022-04-26 07:06
Prototype of progress detail is ready: https://www.figma.com/file/qpUZN3dJqnOcXxPZs36wTj/Config-UI-update?node-id=65%3A1433

**Comment by yumengwang03** [comment] 2022-04-26 08:08
@e2corporation Hi, Julien! Ninghan has designed this feature in Figma in the comment above.

**Comment by klesh** [comment] 2022-04-27 01:31
Backend doesn't hold the historical steps of a task, please check #1423 and you will understand, only the latest one is available from api, the number of `steps` is tweenty-sth for JIRA plugin by default, could be more in the future, it could be quite long... @yumengwang03 @tanninghan

**Comment by tanninghan** [comment] 2022-04-27 11:27
@e2corporation Hi, Julien! Please check the latest prototype here https://www.figma.com/file/qpUZN3dJqnOcXxPZs36wTj/Config-UI-update?node-id=65%3A1433

**Comment by e2corporation** [comment] 2022-04-29 02:43
@tanninghan @yumengwang03 @Startrekzky There are some slight issues with the proposed design changes here, Pipelines can contain one or more Providers (plugins), so placing a singular "Github" and Repository name at the top of the pipeline activity isn't practical because those are tasks that belong the pipeline.

**Comment by klesh** [comment] 2022-05-10 01:57
To be addressed in new design , close it for now.

**Closed by klesh** 2022-05-10 01:57 UTC
Labels: type/question, priority/medium, usability
