### ISSUE TITLE
config-ui: jira issue type mappings and settings disabled, missing rest api proxy

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#1539] opened 2022-04-12 16:11 UTC
## Config-UI / Data Integrations / JIRA
The **JIRA** Settings are not accessble due to missing endpoint for JIRA's REST API Proxy which was previously provided by backend but appears to be missing from main branch, which will make JIRA settings unusable.

## Screenshots
 <img width="1336" alt="Screen Shot 2022-04-12 at 12 06 02 PM" src="https://user-images.githubusercontent.com/1742233/163006618-5fb550ac-9c80-4af5-8a34-84f896e216ae.png">
<img width="746" alt="Screen Shot 2022-04-12 at 12 05 21 PM" src="https://user-images.githubusercontent.com/1742233/163006622-397f220b-99d2-47f4-af98-31e40b5335e8.png">
<img width="773" alt="Screen Shot 2022-04-12 at 12 07 07 PM" src="https://user-images.githubusercontent.com/1742233/163006614-4c92db09-e7a4-4a32-8f59-c9b29fa9c395.png">

**Comment by e2corporation** [comment] 2022-04-12 16:13
As a workaround if a live api endpoint is not available, we'd need a static/fixed list of Issue Types and Field types to use based on a default JIRA Instance.

**Comment by klesh** [comment] 2022-04-13 11:04
@e2corporation I tested on my local machine against merico jira on atlassian.net.
It seems to be working correctly:

![image](https://user-images.githubusercontent.com/61080/163167022-56fb008a-866f-48c5-8762-389649feb8e9.png)

**Comment by klesh** [comment] 2022-04-15 14:17
related to #1614

**Comment by klesh** [comment] 2022-04-18 02:22
@Startrekzky

**Comment by Startrekzky** [comment] 2022-04-18 13:08
It might be caused by a bug by Atlassian, we'll keep watching... Close it for now.

**Closed by Startrekzky** 2022-04-18 13:08 UTC
Labels: type/bug, priority/high
