### ISSUE TITLE
Jira concurrent creation of _raw_jira_api_projects failed

### ISSUE THREAD

**Issue by mappjzc** [merico-dev/lake#1524] opened 2022-04-12 10:39 UTC
## Describe the bug
![image](https://user-images.githubusercontent.com/2921251/162941060-d1aaeb06-0dd4-4ae8-a012-818f191a9eea.png)
When making a concurrent request for the first time, some tasks will create a table concurrently and return an error resulting in failure.
![image](https://user-images.githubusercontent.com/2921251/162941567-f3878438-3e15-41e2-825d-29b48638d57c.png)

## To Reproduce
1. Clear database
2. Execute collection of multiple Jira boards concurrently.

## Expected behavior
Concurrent execution does not affect the first time the table is created.

**Comment by klesh** [comment] 2022-04-14 09:30
Not a bug, we dont support collecting multiple boards against same jira instance in parallel at the point.
However, we shall make documentation for it, will be addressed by #1574

**Closed** 2022-04-14 09:34 UTC
Labels: type/bug
