### ISSUE TITLE
config-ui production build should not use any cdn resource

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#719] opened 2021-11-12 03:20 UTC
## Description
I saw some google cdn css/fonts on production build html. They are inaccessible most of the time in some COUNTRYS

## Describe the solution you'd like
bundle them all into our docker image.

**Comment by joncodo** [comment] 2021-11-12 14:01
Duplicate of #732

**Closed by joncodo** 2021-11-12 14:01 UTC
Labels: proposal, iter4
