### ISSUE TITLE
[Feat][ts] use redis pub sub to emit service event

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#159] opened 2021-08-09 08:53 UTC
a message broker would be helpful, and we have the Redis for task queue
instead of import some message queue service Redis is easier and cheeper 

## HOW

```
// app.module.ts
@Module({
  imports: [
    EventsModule,
    SampleService,
   ObserverService
  ],
  providers: [],
})
export class AppModule {}

//sample.service.ts
@Injectable()
export class SampleService {
  constructor(private eventsService: EventsService) {}

  async startTask(): Promise<void> {
        const info = this.doSomeTask();
        this.eventsService.emit('Sampe:TaskStart', info);
  }
}
//observer.service.ts
@Injectable()
export class ObserverService {
  constructor(private eventService: EventsService) {
     this.eventsService.on('Sampe:TaskStart', this.handleTaskStart)
  }

  async handleTaskStart(info): Promise<void> {
     console.info('the task is start', info);
  }
}

```

## Tests

```
\\e2e tests
\\ add redis mock
jest.mock('ioredis', () => {
  return {
    default: require('ioredis-mock/jest'),
  };
});

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [EventsModule],
    }).compile();

    app = moduleFixture.createNestMicroservice(moduleFixture);
    await app.init();
    const sub = app.get('REDIS_SUB_CLIENT');
    const subSyncClient = sub.createConnectedClient();
    const pub = app.get('REDIS_PUB_CLIENT');
   //change the pub publish method with mocked client publish
    jest.spyOn(pub, 'publish').mockImplementation((env, message) => {
      return subSyncClient.publish(env, message);
    });
  });

 it("the event e2e tests", (done) => {
   // mock the callback func to  validate the event data
    const mockedFuc = jest.fn().mockImplementation((value) => {
      expect(value).toEqual({ ut: 'test' });
      //use done to make sure function be called
      done();
      return;
    });
})

```

**Comment by joncodo** [comment] 2021-08-12 14:47
@jaxzhou I am closing this as a duplicate of #154 . Feel free to re-open and tell me how they are different.

**Closed by joncodo** 2021-08-12 14:47 UTC
Labels: proposal
