### ISSUE TITLE
blueprint name should be updated when click on Hourly Daily Weekly

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1622] opened 2022-04-15 12:27 UTC
## Description

![Snipaste_2022-04-15_20-20-04](https://user-images.githubusercontent.com/61080/163570475-3e92a9bb-f62f-483f-9a0f-d2c2457eef41.png)
![Snipaste_2022-04-15_20-20-18](https://user-images.githubusercontent.com/61080/163570477-c9c6d4a9-8db2-4621-94f8-0582a17377be.png)

## Describe the solution you'd like
name ought to be updated automatically if user never changed it.

**Comment by e2corporation** [comment] 2022-04-15 13:00
Duplicate of #1616

**Closed** 2022-04-15 13:17 UTC
Labels: type/feature-request
