### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid because:Unsupported config option for services.mysql: 'platform'

### ISSUE THREAD

**Issue by matthewxuda** [merico-dev/lake#707] opened 2021-11-11 00:19 UTC
## Question
when i setup,  i meet flow issue:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.mysql: 'platform'

## Screenshots
$ cat ./docker-compose.yml
version: "3"
services:
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
      - ./grafana/img:/usr/share/grafana/public/img/lake:ro
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_LIVE_ALLOWED_ORIGINS=*
    restart: always
    depends_on:
      - mysql
  devlake:
    image: mericodev/lake:0.3.0
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - ./.env
    restart: always
    depends_on:
      - grafana
  config-ui:
    image: mericodev/config-ui:0.3.0
    ports:
      - 127.0.0.1:4000:4000
    environment:
      - ENV_FILEPATH=/.env
      - DEVLAKE_ENDPOINT=http://devlake:8080
      - GRAFANA_PORT=3002/d/RXJZNpMnz/homepage?orgId=1
    volumes:
      - ./.env:/.env:rw
volumes:
  mysql-storage:
  grafana-storage:

## Additional context
Add any other context here.

**Comment by narrowizard** [comment] 2021-11-11 02:19
What is your docker-compose version? Try to
- Upgrade docker-compose to 1.29.x
- Or downgrade the `version` property to 2.4 in [docker-compose.yml#L1](https://github.com/merico-dev/lake/blob/main/docker-compose.yml#L1)

**Comment by matthewxuda** [comment] 2021-11-11 10:09
thanks :), it work

**Comment by narrowizard** [comment] 2021-11-12 02:11
Closed this issue since the problem is fixed. Feel free to reopen it if there is any more questions about this.

**Closed by narrowizard** 2021-11-12 02:11 UTC
Labels: question
